### ISSUE TITLE
Just logged in got this issue

### ISSUE THREAD

**Issue by JeyCraft** [zRxnx/zrx_utility#1]
![image](https://github.com/zRxnx/zrx_utility/assets/63811758/31d6951f-3634-46de-8051-bf6e5e6662af)

So when i join on the server i got this messange. :s

**Comment by zRxnx** [comment]
Same issue as the armour one

**Comment by JeyCraft** [comment]
Yea did u checked where it could come from?

**Comment by zRxnx** [comment]
Missing esx data

**Comment by JeyCraft** [comment]
and which esx data is missing? 😓

**Comment by zRxnx** [comment]
Status

**Comment by JeyCraft** [comment]
oh rip i dont use esx status 😅 What/where do i need to change to use it? Bc i using cd_playerhud

**Comment by zRxnx** [comment]
Idk, i dont just support random resources that is not worth it.

When i am at home i will add some checks so it wont happen again

**Comment by JeyCraft** [comment]
ok cool. <3 Would be nice if it could be used with other status systems than esx_status (: If this is what u talking about "status"

**Comment by zRxnx** [comment]
Fixed in the next update
